services:
  - type: web
    name: nuxt3-sqlite-app
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.git
    # branch: main
    dockerfilePath: ./Dockerfile
    # autoDeploy: true
    plan: free

    # 環境変数
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_HOST
        value: "0.0.0.0"
      - key: NUXT_PORT
        value: "3000"
      - key: DATABASE_URL
        value: file:/app/.data/dev.db
      - key: AUTH_SECRET
        fromSecret: AUTH_SECRET_VALUE # RenderのSecretsで AUTH_SECRET_VALUE という名前で値を設定

    # 永続ディスクの設定 (SQLiteデータ保存用)
    disks:
      - name: sqlite-data
        mountPath: /app/.data
        sizeGB: 1
